### ISSUE TITLE
Open Tiff and Convert to JPG

### ISSUE THREAD

**Issue by eoherrer** [Beyka/Android-TiffBitmapFactory#16]
Hi!,

I'm trying to use the decode process, but returns null the bitmap.

File file = new File("/storage/emulated/0/Android/data/Temp/50a.tif");

//Read data about image to Options object
            TiffBitmapFactory.Options options = new TiffBitmapFactory.Options();
            options.inJustDecodeBounds = true;

            Bitmap bmp = null;
            bmp = TiffBitmapFactory.decodeFile(file, options);

Can you please tell me if I missing something.

**Comment by Beyka** [comment]
When inJustDecodeBounds set to true - bitmap not decided, but meta-information read. Set this variable to false and decoder will return bitmap

**Comment by eoherrer** [comment]
Awesome Thanks!!!!
