### ISSUE TITLE
Error while running in release mode

### ISSUE THREAD

**Issue by hlaurent** [Beyka/Android-TiffBitmapFactory#18]
Hi,
Thank you for this great library.
I am using it with Graddle: compile 'com.github.beyka:androidtiffbitmapfactory:0.9.7.2'
My Compile SDK version is 21  and targetSdkVersion is 19.

It is working fine on my Nexus 9 runnig Android 7.1.1 that I use for testing  when I run my app in debug mode.
When I generate a signed apk in  release mode, it fails with the following error code.
05-17 17:03:58.851 6939-6939/? A/art: art/runtime/java_vm_ext.cc:470]   native: #06 pc 0000000000009910  /data/app/com.sailgrib_wr.paid-1/lib/arm64/libtifffactory.so (_ZN13NativeDecoder12createBitmapEii+852)
05-17 17:03:58.851 6939-6939/? A/art: art/runtime/java_vm_ext.cc:470]   native: #07 pc 0000000000007b20  /data/app/com.sailgrib_wr.paid-1/lib/arm64/libtifffactory.so (Java_org_beyka_tiffbitmapfactory_TiffBitmapFactory_nativeDecodePath+80)
05-17 17:03:58.851 6939-6939/? A/art: art/runtime/java_vm_ext.cc:470]   native: #08 pc 00000000000d10f0  /data/app/com.sailgrib_wr.paid-1/oat/arm64/base.odex (Java_org_beyka_tiffbitmapfactory_TiffBitmapFactory_nativeDecodePath__Ljava_lang_String_2Lorg_beyka_tiffbitmapfactory_TiffBitmapFactory_00024Options_2Lorg_beyka_tiffbitmapfactory_IProgressListener_2+204)
Can you help?
thanks,
Henri

**Comment by Beyka** [comment]
Hello. Do you use proguard for release build? If so - add next line to you proguard config
-keep class org.beyka.tiffbitmapfactory.**{ *; }

**Comment by hlaurent** [comment]
Thanks, that was the issue.
It now works beautifully.
