### ISSUE TITLE
compiled project

### ISSUE THREAD

**Issue by krudos** [Beyka/Android-TiffBitmapFactory#2]
do you have a link to the library already compiled and ready to add to a android project?

**Comment by Beyka** [comment]
Nope. But compiling is simple for any environment(linux, windows, mac).
You have some problem with compiling?

**Comment by krudos** [comment]
i not understand yet how to add this kind of library to a android studio project

to compile i need ndk
but for the IDE do i have to use eclipse?
could you add some instructions to compile the project

thank you

**Comment by krudos** [comment]
i got it run

i have to download ndk
and compile it with ndk-build
thenk copy the compiles libs to my project and also the java files

**Comment by Beyka** [comment]
1) First of all you need to download sources;
2) after that add to your IDE (For Studio: Project Settings - check main module - goto dependencies tab - add module dependency);
3) open terminal, goto <Your project path>/Android-TiffBitmapFactory(or how you name this module)
4) Run command: ndk-build NDK_PROJECT_PATH=src/main

**Comment by Beyka** [comment]
Project now on jcentral, so you can add this dependency: 
compile 'com.github.beyka:androidtiffbitmapfactory:0.6'
