### ISSUE TITLE
there is a tif image make this crash

### ISSUE THREAD

**Issue by y649950268** [Beyka/Android-TiffBitmapFactory#22]
[tiffTest111.zip](https://github.com/Beyka/Android-TiffBitmapFactory/files/1167188/tiffTest111.zip)

I dont know why this picture cause  crash ! can you give me some suggest?

**Comment by Beyka** [comment]
Hello. Will investigate this issue. I think that there is some issue in image and library could not handle it. Any way I'll do my best to fix this

**Comment by Beyka** [comment]
Fixed in version 0.9.7.6. Please use this version.
Also, could you tell me what software you have used to create this image?

**Comment by y649950268** [comment]
Thank you to fix it ! fax software on the Brother printer  create this image! such a small size image. can you explain what happened?

**Comment by Beyka** [comment]
Your software creating image with COMPRESSION_CCITTRLE(CCITT modified Huffman RLE) compression scheme, but not writing TIFFTAG_BITSPERSAMPLE(bits per sample tif tag). If this tag is not 1, 4, 8 or 16 - library should show error, but for some reason calling of java method from C++ code that should show error in logcat leads to crash. 
Anyway in TIFF specifications TIFFTAG_BITSPERSAMPLE default is 1, so I just changed default value  for this variable and changed showing of error in logcat. 
I believe that those fixes will help

**Comment by y649950268** [comment]
Thank you~
