### ISSUE TITLE
arm64-v8a

### ISSUE THREAD

**Issue by kankyou** [Beyka/Android-TiffBitmapFactory#3]
Is arm64-v8a supported?

**Comment by Beyka** [comment]
For now arm64-v8a not supported. Sorry.
Supported platforms: x86 armeabi armeabi-v7a mips

**Comment by Beyka** [comment]
Hello, @kankyou, If you still use my lib, here is good news about x64 support: https://github.com/Beyka/Android-TiffBitmapFactory/issues/10
