### ISSUE TITLE
Noise is displayed in compressed format of CCITT.

### ISSUE THREAD

**Issue by tadacchi** [Beyka/Android-TiffBitmapFactory#30]
Hi,

I noticed that I was creating an application using this library.
If you import a file compressed in fax format (CCITT), it will introduce noise.
A similar phenomenon was also seen in "B Tiff Viewer" you developed.

The files used are as follows
https://www.fileformat.info/format/tiff/sample/index.htm
* G31DS.TIF
* G32DS.TIF

Please tell me how to eliminate the noise.
Regards.

**Comment by Beyka** [comment]
Hello. This problem is appears on ARM processors.
This is problem of libtiff, so you can write there.
