### ISSUE TITLE
About License 

### ISSUE THREAD

**Issue by tadacchi** [Beyka/Android-TiffBitmapFactory#31]
Hi,

Let me check about the license.
Beyka-san is written as 
`https://github.com/Beyka/Android-TiffBitmapFactory/issues/7`
> In future I will try to remove GPL code from project to use MIT license

Is it MIT license now?

If it is not MIT license, 
what does "licences = ['MIT']" in build.gradle mean?

Regards.

**Comment by Beyka** [comment]
yes, It is MIT

**Comment by tadacchi** [comment]
Thank you for answering.

"license.txt" is notation like GPL,
Does that mean you do not have to worry about it?

Since I want to use it for commercial use, I am asking a question.

Regards.

**Comment by Beyka** [comment]
I didn't know that I have license.txt file :) It was created somewhere in past by some other person. I think that I will delete it

**Comment by Beyka** [comment]
But I think that it should be MIt - you can use this lib in any product in any way you want, but not forget to add link to this github repo

**Comment by Beyka** [comment]
Now changed text of license.txt

**Comment by tadacchi** [comment]
Thank you very much.

> you can use this lib in any product in any way you want, but not forget to add link to this github repo

I understand.
Do not forget to link.

Close the issue.
