### ISSUE TITLE
Error converting from jpg to Tiff CCITTFAX4 or FAX3

### ISSUE THREAD

**Issue by iguron** [Beyka/Android-TiffBitmapFactory#32]
Hi,

I was using your excellent library since many many months ago. After relaunching the app I was developing and updating to the latest version of the library (I was using 0.9.7.5 or lower), I found that the conversion of a single JPG is not ok.
I´m getting a noise unreadable image.

I´m using the piece of code explained in the example and tutorial. And I hardly beleive that this piece of code was working before...

any help?

**Comment by Beyka** [comment]
Hello. I will check.

**Comment by Beyka** [comment]
Please, check version 0.9.8.7

**Comment by iguron** [comment]
SOLVED!!!! Thanks for the effort and quick answer!!!!

**Comment by GrayCygnus** [comment]
@iguron if your Issue was solved please close this issue as such, so users can see this was solved.
