### ISSUE TITLE
Make sure library is 64 bit compatible

### ISSUE THREAD

**Issue by jfacoustic** [Beyka/Android-TiffBitmapFactory#39]
Coming up pretty soon, Android will require apps to be 64bit.

**Comment by Nikhilngarg** [comment]
Hey Any idea when we'll be able to get the 64 bit compatible lib?

**Comment by mintapp** [comment]
I think the author added x64 support:
it was on that branch - https://github.com/Beyka/Android-TiffBitmapFactory/tree/x64-support/src/main/jni/libs which merged into master.

i need it too, but didnt check it yet.

**Comment by noamamiran** [comment]
I think the author added x64 support:
it was on that branch - https://github.com/Beyka/Android-TiffBitmapFactory/tree/x64-support/src/main/jni/libs which merged into master.

i need it too, but didnt check it yet.

**Comment by Beyka** [comment]
Library support x64 from first release.  Full list of available architecture support:
ARM v7
ARM v8-64
X86
X86-64
MIPS
MIPS-64
