### ISSUE TITLE
Usage issue

### ISSUE THREAD

**Issue by Devin-Chen** [Beyka/Android-TiffBitmapFactory#4]
Hi Beyka,

I am having issue using your module. I tried to install it through gradle dependencies (compile 'com.github.beyka:androidtiffbitmapfactory:0.6'), then following the usage sample you wrote. However, I couldn't access the options properties or decodeFile in the TiffBitmapFactory object. Do you know what could be the issue?

Thanks,
Devin

**Comment by Beyka** [comment]
Hello, Devin! Did you add this import:

``` Java
import org.beyka.tiffbitmapfactory.TiffBitmapFactory;
```

?

**Comment by Devin-Chen** [comment]
Hi Beyka,

Thanks for the quick response. I added it. I can create the options object, but not access any of the fields. I am using Android Studio. 

Thanks,
Devin

**Comment by Devin-Chen** [comment]
Hi Beyka,

I cleaned the project and rebuilt gradle, and it looks fine now. Sorry for the false alarm.

Best,
Devin
