### ISSUE TITLE
Image noise problem in CPU/ABI x86_64

### ISSUE THREAD

**Issue by gitpushyj** [Beyka/Android-TiffBitmapFactory#42]
In x86_64 Device, Some Tiff has image noising.

x86 device)
![x86](https://user-images.githubusercontent.com/18481078/71708316-c154ee80-2e33-11ea-996f-d07abea830bc.png)

x86_64 device)
![x86_64](https://user-images.githubusercontent.com/18481078/71708317-cc0f8380-2e33-11ea-81e9-a7fb5c37b076.png)
 
How can i fix it? Should i write some code to fix it??

**Comment by Beyka** [comment]
This is problem inside libtif. I don't know how to fix it.
