### ISSUE TITLE
decodeFile returned null

### ISSUE THREAD

**Issue by Devin-Chen** [Beyka/Android-TiffBitmapFactory#5]
Hi Beyka,

I am now having issue getting decodeFile to work. I used a test Tiff (1640x1240), set options.inJustDecodeBounds = true, and called decodeFile(file, options). There was no exception, but the Bitmap returned was null. 

I then tried importing your source as module (not from gradle), but same result. However, android studio warned that it could not resolve corresponding JNI function of nativeDecodePath in TiffBitmapFactory.java.

I am using NDK 10e for the native code compilation (which also warns of non-system libraries in linker flags for libjpeg-x86.a and libjpeg.a. 

Do you know how I can resolve this issue?

Thanks,
Devin

**Comment by Beyka** [comment]
options.inJustDecodeBounds = true
this options says to factory not decode file, but get all data from it: width, height, count of directories(count of images in one file) and image orientation. With this options you can calculate sample size, select what image to decode, etc.
For decoding you should set options.inJustDecodeBounds  to false and than call

``` Java
Bitmap bmp = TiffBitmapFactory.decodeFile(file, options);
```

or just call

``` Java
Bitmap bmp = TiffBitmapFactory.decodeFile(file);
```

without options - it will be created with default parameters.

Also you can check javadoc for this method:
/**
         \* If set to true, the decoder will return null (no bitmap), but
         \* the out... fields will still be set, allowing the caller to query
         \* the bitmap without having to allocate the memory for its pixels.
         */

**Comment by Devin-Chen** [comment]
Thanks for the explanation Beyka. It's working now.

Devin
