### ISSUE TITLE
jcenter repository shut down

### ISSUE THREAD

**Issue by AGDownie** [Beyka/Android-TiffBitmapFactory#52]
According to JFrog, the JCenter repository ceased serving packages on February 1st 2022, which means your library is no longer accessible and now gives the following error in when syncing Gradle dependencies in Android Studio:  "Failed to resolve: com.github.beyka:androidtiffbitmapfactory:0.9.8.8"

The artifact is still searchable in Maven, giving the URL  [https://mvnrepository.com/artifact/com.github.beyka/androidtiffbitmapfactory/0.9.8.8]()
However, the link to the library on JCenter [https://jcenter.bintray.com/com/github/beyka/androidtiffbitmapfactory/0.9.8.8/androidtiffbitmapfactory-0.9.8.8.aar]() gives a 403 Forbidden error, confirming that the JCenter repository has been closed down.

Can you advise if you are intending to migrate the library to MavenCentral to keep your library alive, or perhaps make the library available as a direct download from the GitHub repository.

Thanks in advance.

**Comment by Beyka** [comment]
Will migrate in nearest 2-3 days. I thought that nobody uses this lib

**Comment by AGDownie** [comment]
Thanks for the response.

To be honest, I don't yet use the library, but was hoping to try it out.

Unfortunately, it turns out I wouldn't be able to use it anyway, as it doesn't appear to emulate the decodeBitmap(byte[]) or decodeBitmap(InputStream) methods, which I need, so don't feel you have to migrate it on my account.

If I have the time, I might fork it to provide the necessary methods.

**Comment by lasat** [comment]
We are using the library. :-)

**Comment by Beyka** [comment]
I started add supporting for inputStream but stop the work a year ago. Also there is almost done changes for support Android Q. But have no time. If you will add this methods, you can make pullrequest if you want)

**Comment by Beyka** [comment]
Moved to maven central
implementation 'io.github.beyka:Android-TiffBitmapFactory:0.9.8.7'

**Comment by odeyatwi** [comment]
I'm getting 401 Auth error
`Could not HEAD 'https://jitpack.io/com/github/beyka/androidtiffbitmapfactory/0.9.8.7/androidtiffbitmapfactory-0.9.8.7.pom'. Received status code 401 from server: Unauthorized`

**Comment by Beyka** [comment]
> I'm getting 401 Auth error

Checked few minutes ago. All ok. Gradle able to downalod all artifact

**Comment by AGDownie** [comment]
Thanks, Beyka.  I have confirmed I am now able to download and sync the library in my project.
