### ISSUE TITLE
 fdsan: attempted to close file descriptor 81, expected to be unowned, actually owned by ParcelFileDescriptor 0xebcfa4c

### ISSUE THREAD

**Issue by therealbluepandabear** [Beyka/Android-TiffBitmapFactory#54]
I am getting the following when trying to decode a TIFF file:

```
2022-08-11 17:47:41.526 9426-9426/com.therealbluepandabear.pixapencil A/libc: fdsan: attempted to close file descriptor 81, expected to be unowned, actually owned by ParcelFileDescriptor 0xebcfa4c
2022-08-11 17:47:41.526 9426-9426/com.therealbluepandabear.pixapencil A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9426 (bear.pixapencil), pid 9426 (bear.pixapencil)
```

Code:

```
TiffBitmapFactory.decodeFileDescriptor(parcelFileDescriptor.fd, options)
```

**Comment by Beyka** [comment]
Check is this FileDescriptor not opened in one more place.

**Comment by adachi-hideki** [comment]
Same thing happens to me.
Occurs on android 11 and later.
It seems that the reason is that it is closed in the destructor of NativeDecoder.
NativeDecoder::~NativeDecoder()
{
     LOGI("Destructor");
     if (image) {
         TIFFClose(image);
         image = NULL;
     }

**Comment by therealbluepandabear** [comment]
Is there any way to fix it?

**Comment by adachi-hideki** [comment]
This is clearly a remnant of decodePath, so if you specify the filedescriptor of parcelFileDescriptor, deleting it without permission is a bug, so I would like you to fix it.
I don't know the impact on others, but if it's only decoding, it can be avoided by using the NDK that ndk-builds the one that commented out "TIFFClose(image)" from the destructor of NativeDecoder, but it's a little troublesome.

**Comment by Beyka** [comment]
Deleted closing of IMAGE in native if it was oppened from FD.
Please try 0.9.9.1 build

**Comment by therealbluepandabear** [comment]
> @therealbluepandabear @adachi-hideki Deleted closing of IMAGE in native if it was oppened from FD. Please try 0.9.9.1 build

What is 0.9.9.1 build?

**Comment by therealbluepandabear** [comment]
I quit android dev, but I trust that it's probably fixed, this can be closed.
