### ISSUE TITLE
Group 4 compression support

### ISSUE THREAD

**Issue by gussorribas** [Beyka/Android-TiffBitmapFactory#6]
Hi! 
I am building an Android App and I need to compress an image in group 4. But I am not seeing the option in TiffSaver.CompressionMode. Is there any way I can call COMPRESSION_CCITTFAX4 ??

**Comment by Beyka** [comment]
Hello. I apologize for the long response time. I have not add this compression mode to library, but I will add it tomorrow

**Comment by Beyka** [comment]
Also libtiff may have some bugs with this format. I check all compression mods that libtiff is supporting(http://www.awaresystems.be/imaging/tiff/tifftags/compression.html) and left only mods that can be decoded by GIMP

**Comment by Beyka** [comment]
Hello. my apologize for long answer time. I didn't added support for most compression mods of libtiff(http://www.awaresystems.be/imaging/tiff/tifftags/compression.html) cause it's not work. Libtiff requires additional configuration and additional dependencies to work with most of compression mods. This feature will be added in future release.

**Comment by iguron** [comment]
+1 This compresion method Group 4 could be really interesting also for me.

**Comment by Beyka** [comment]
Sorry guys, I'm working on it. As soon as I added support for COMPRESSION_CCITTFAX4 I will leave message in this topic

**Comment by Beyka** [comment]
@iguron @gussorribas 
In version 0.9.6 COMPRESSION_CCITTFAX4 and COMPRESSION_CCITTFAX3 has been added

**Comment by iguron** [comment]
Great!!!!!!!!
--
Igotz Urgoitia Ondiz
@:igotz.urgoitia@gmail.com
T:618967435

**Comment by Beyka** [comment]
So you can check it and if there is some kind of problems - please, write it down to this topic or new topic.

**Comment by iguron** [comment]
Great I will do it…

--
Igotz Urgoitia Ondiz
@:igotz.urgoitia@gmail.com
T:618967435
