### ISSUE TITLE
Commercial Use

### ISSUE THREAD

**Issue by chrissd23** [Beyka/Android-TiffBitmapFactory#7]
Hi , is there any possibility to use this great library for commercial use ? 

Because the problem is the gpl license.

**Comment by Beyka** [comment]
Hello, chrissd23. As for my own code - you can use it where you want and as you want but with link to this repo. 
But in project uses libtiff library and I don't know What type of license they have and tifffastcrop that has GPL license.

**Comment by chrissd23** [comment]
Hello, 
thanks for your answer. :)  
I know that libtiff use BSD license. So I have to contact the author of tifffastcrop to ask for commercial use...? 

Thanks for the great library 👍

**Comment by Beyka** [comment]
As I understand GPL - yes, You need to contact author of tifffastcrop or just remove code based on tifffastcrop from library.

**Comment by chrissd23** [comment]
Ok
I will contact the author :). 

Oh I can't remove this code because it is for incremental read of tiff files ... :(

**Comment by Beyka** [comment]
yeah, I know it, it was a joke :)

**Comment by Beyka** [comment]
In future I will try to remove GPL code from project to use MIT license

**Comment by chrissd23** [comment]
Oh that would be great!!!! :)
