### ISSUE TITLE
Create multipaged tiff

### ISSUE THREAD

**Issue by jaison043** [Beyka/Android-TiffBitmapFactory#8]
hi is there an option where i can create a multi paged tiff depending on the number of png images?

**Comment by Beyka** [comment]
Hello, @jaison043, sorry for late answer, I didn't so this issue. No there is no supporting of creating multipage tiff files, but it will be soon, just after I will finish with x64 support

**Comment by luckcoolla** [comment]
Now it's possible, right?
https://github.com/Beyka/Android-TiffBitmapFactory#adding-page-to-existing-tiff-file

So, the ticket can be closed
