### ISSUE TITLE
Question: couldn't find "libtiff.so"

### ISSUE THREAD

**Issue by FranciscoBartilotti** [Beyka/Android-TiffBitmapFactory#9]
Hi, I have a problem when running in a Moto Droid Turbo 2:

E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader
[DexPathList[[zip <filePath>-1/base.apk"],nativeLibraryDirectories=[<filePath>-1/lib/arm64,
<filePath>-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libtiff.so"

Any chance someone could explain me what is missing?

Thank you for your time.

**Comment by Beyka** [comment]
Hello. Unfortunately libtiff haven't support for arm64 and arm64v8 platforms.  I'm working on it.

**Comment by FranciscoBartilotti** [comment]
I see, thank you very much.

**Comment by bjccoronel** [comment]
Hi @Beyka, this is a great work, do you have an update for the arm64v8 platform? 
Thanks in advanced.

**Comment by Beyka** [comment]
Hello, @barryjohncoronel! Yes I have update. Now I'm testing build that should support all platforms. So in few day I will upload new branch for bets testing. Check this topic for updates

**Comment by Beyka** [comment]
@barryjohncoronel, here is information about x64 support: https://github.com/Beyka/Android-TiffBitmapFactory/issues/10
